// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdnZysBayzGE0iGteRA9qE0d9Dixh18k',
    appId: '1:153192912808:web:64998174ecfa6bc8712f9d',
    messagingSenderId: '153192912808',
    projectId: 'peoplesync-8c0c3',
    authDomain: 'peoplesync-8c0c3.firebaseapp.com',
    storageBucket: 'peoplesync-8c0c3.firebasestorage.app',
    measurementId: 'G-C3TF20VF9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAKiX8YT5OdEYVz7QZPtgorqUit7I1Dg',
    appId: '1:153192912808:android:11700a5a1eb50f03712f9d',
    messagingSenderId: '153192912808',
    projectId: 'peoplesync-8c0c3',
    storageBucket: 'peoplesync-8c0c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO0wjhK7CmfhlY1EoowbE2VD65wpz2SeY',
    appId: '1:153192912808:ios:88f7cd501b3c0f26712f9d',
    messagingSenderId: '153192912808',
    projectId: 'peoplesync-8c0c3',
    storageBucket: 'peoplesync-8c0c3.firebasestorage.app',
    iosClientId: '153192912808-7q76b2ga2fbn3omq1gee96vat17g3gnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.peoplesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO0wjhK7CmfhlY1EoowbE2VD65wpz2SeY',
    appId: '1:153192912808:ios:88f7cd501b3c0f26712f9d',
    messagingSenderId: '153192912808',
    projectId: 'peoplesync-8c0c3',
    storageBucket: 'peoplesync-8c0c3.firebasestorage.app',
    iosClientId: '153192912808-7q76b2ga2fbn3omq1gee96vat17g3gnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.peoplesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHdnZysBayzGE0iGteRA9qE0d9Dixh18k',
    appId: '1:153192912808:web:bc58a2dbc6f50c62712f9d',
    messagingSenderId: '153192912808',
    projectId: 'peoplesync-8c0c3',
    authDomain: 'peoplesync-8c0c3.firebaseapp.com',
    storageBucket: 'peoplesync-8c0c3.firebasestorage.app',
    measurementId: 'G-8FK4P0JRND',
  );
}
