# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Configurar Flutter en lugar de solo Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Puedes cambiar a 'beta' o 'dev' si es necesario

      # 2. Obtener dependencias con flutter pub get
      - name: Install dependencies
        run: flutter pub get

      # 3. Verificar el formato de Flutter (opcional, pero recomendado)
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # 4. Analizar el código de Flutter
      # Considera pasar '--fatal-infos' para un análisis más estricto.
      - name: Analyze project source
        run: flutter analyze

      # 5. Ejecutar las pruebas de Flutter
      - name: Run tests
        run: flutter test
